---
kind: pipeline
name: default

steps:
  - name: tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: submodules
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update
    depends_on:
      - tags

  - name: lint
    image: golangci/golangci-lint:v1.39.0
    commands:
      - make lint
    depends_on:
      - submodules

  - name: test
    image: golang:latest
    commands:
      - make test
    depends_on:
      - submodules

  - name: build
    image: goreleaser/goreleaser:v0.162.0
    commands:
      - make build
    depends_on:
      - lint
      - test
    when:
      event:
        exclude:
          - tag

  - name: release
    image: goreleaser/goreleaser:v0.162.0
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - goreleaser release --rm-dist --parallelism=1
    depends_on:
      - lint
      - test
    when:
      event:
        - tag
