---
kind: pipeline
name: default

steps:
  - name: tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: submodules
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update

  - name: go-bindata
    image: golang:latest
    commands:
      - (cd /tmp; go get -u github.com/go-bindata/go-bindata/...)
      - go-bindata -pkg assets -o assets/bindata.go -nomemcopy /bin/true

  - name: lint
    image: golangci/golangci-lint:latest
    commands:
      - make lint
    depends_on:
      - go-bindata

  - name: test
    image: golang:latest
    commands:
      - make test
    depends_on:
      - go-bindata

  - name: clean
    image: golang:latest
    commands:
      - make clean
      - git checkout -- .
    depends_on:
      - lint
      - test

  - name: build
    image: goreleaser/goreleaser:v0.159.0
    commands:
      - (cd /tmp; go get -u github.com/go-bindata/go-bindata/...)
      - make build
    depends_on:
      - submodules
      - clean
    when:
      event:
        exclude:
          - tag

  - name: release
    image: goreleaser/goreleaser:v0.159.0
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - (cd /tmp; go get -u github.com/go-bindata/go-bindata/...)
      - goreleaser release --rm-dist --parallelism=1
    depends_on:
      - submodules
      - clean
    when:
      event:
        - tag
