---
project_name: wg-quicker

builds:
  - id: amd64
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make wireguard-go GOARCH={{.Arch}}

  - id: arm64
    env:
      - CGO_ENABLED=0
    goarch:
      - arm64
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make wireguard-go GOARCH={{.Arch}}

  - id: "386"
    env:
      - CGO_ENABLED=0
    goarch:
      - "386"
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make wireguard-go GOARCH={{.Arch}}

  - id: arm-5
    env:
      - CGO_ENABLED=0
    goarch:
      - arm
    goarm:
      - "5"
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make wireguard-go GOARCH={{.Arch}} GOARM=5

  - id: arm-6
    env:
      - CGO_ENABLED=0
    goarch:
      - arm
    goarm:
      - "6"
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make wireguard-go GOARCH={{.Arch}} GOARM=6

  - id: arm-7
    env:
      - CGO_ENABLED=0
    goarch:
      - arm
    goarm:
      - "7"
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make wireguard-go GOARCH={{.Arch}} GOARM=7

archives:
  - format: tar.gz
    id: tar.gz
    replacements:
      darwin: macos

  - format: binary
    id: binary-archive
    replacements:
      darwin: macos

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^lint:"
      - "^happy linting"

release:
  github:
    owner: xsteadfastx
    name: wg-quicker

nfpms:
  - formats:
      - apk
      - deb
      - rpm
    replacements:
      386: i386
    homepage: https://git.xsfx.dev/xsteadfastx/wg-quicker
    maintainer: Marvin Preuss <marvin@xsteadfastx.org>
    bindir: /usr/local/bin
    contents:
      - src: init/openrc/wg-quicker.init
        dst: /etc/init.d/wg-quicker
        packager: apk
        file_info:
          mode: 0755
          owner: root
          group: root
      - src: init/systemd/wg-quicker@.service
        dst: /etc/systemd/system/wg-quicker@.service
        packager: deb
      - src: init/systemd/wg-quicker@.service
        dst: /etc/systemd/system/wg-quicker@.service
        packager: rpm

brews:
  - name: wg-quicker
    ids:
      - tar.gz
    tap:
      owner: xsteadfastx
      name: homebrew-tap
    commit_author:
      name: Marvin Steadfast
      email: marvin@xsteadfastx.org
    homepage: https://git.xsfx.dev/xsteadfastx/wg-quicker
    install: |
      bin.install "wg-quicker"
    test: |
      system "#{bin}/wg-quicker version"
