---
project_name: wg-quicker
gitea_urls:
  api: https://git.xsfx.dev/api/v1/

builds:
  - id: amd64
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make generate GOARCH={{.Arch}}

  - id: arm64
    env:
      - CGO_ENABLED=0
    goarch:
      - arm64
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make generate GOARCH={{.Arch}}

  - id: 386
    env:
      - CGO_ENABLED=0
    goarch:
      - 386
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make generate GOARCH={{.Arch}}

  - id: arm-5
    env:
      - CGO_ENABLED=0
    goarch:
      - arm
    goarm:
      - 5
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make clean
        - make generate GOARCH={{.Arch}} GOARM=5

  - id: arm-6
    env:
      - CGO_ENABLED=0
    goarch:
      - arm
    goarm:
      - 6
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make generate GOARCH={{.Arch}} GOARM=6

  - id: arm-7
    env:
      - CGO_ENABLED=0
    goarch:
      - arm
    goarm:
      - 7
    goos:
      - linux
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X go.xsfx.dev/wg-quicker/cmd.version={{.Version}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.commit={{.ShortCommit}}"
      - "-X go.xsfx.dev/wg-quicker/cmd.date={{.Date}}"
    hooks:
      pre:
        - make generate GOARCH={{.Arch}} GOARM=7

archives:
  - replacements:
      darwin: macos

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - formats:
      - apk
      - deb
      - rpm
    replacements:
      386: i386
    homepage: https://git.xsfx.dev/xsteadfastx/wg-quicker
    maintainer: Marvin Preuss <marvin@xsteadfastx.org>

brews:
  - name: wg-quicker
    github:
      owner: xsteadfastx
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Marvin Preuss
      email: marvin@xsteadfastx.org
    homepage: https://git.xsfx.dev/xsteadfastx/wg-quicker
    test: |
      system "#{bin}/wg-quicker version"
